export const ITEMS = {
    config: {
        collection: "GFiHUuxU4etmXcpqqUXPx7ecZZYr3j6NYqAJ2H7wP4KB",
        helper_collection: ""
    },
    blueKey: {
        amount: 100_000,
        glb:  "https://arweave.net/4o3efioXVTMYAXCerFtpiYBdDzVOuPb4VxQGHsncfk4",
        png:  "https://arweave.net/gN9IcD4T4l7d71c1v5xTlVsvn0ByT-QyRNI3DE_002c",
        json: "https://arweave.net/a2vqdvu2WS05nxQJIrtptEPLE2-jM5J-4THOyii379A",
        mint: "3ZEA8occPSr7t6w4vrLMS2NFMsibu4pvrq4mwY9prEFe",
    },
    greenKey: {
        amount: 100_000,
        glb:  "https://arweave.net/tkoOiBTlSuX-Y6W9lR2UB-3VVGyxMijnGe4Ld2k8fU0",
        png:  "https://arweave.net/_MGeR0cyzolMNtWYrIDRQCEhi-27UmlizGVNhy7Fih4",
        json: "https://arweave.net/RIMjOja2kLjb6N8wtK_fwhEDsEru7rxKz8zRwKgZ4OM",
        mint: "74aGRDhYobhZTxxejjoRo2KFAjJy8q1kGgbSYcGDyiJi",
    },
    purpleKey: {
        amount: 100_000,
        glb:  "https://arweave.net/yKQlwpI5K7PdDAmCfmFR6v_oWzKh0wjFtlDF25QtRks",
        png:  "https://arweave.net/SIO8pPCSCsqg0kM9fGNXOQohDHhNPJ8n8Lwv_tjyfQg",
        json: "https://arweave.net/W8a5bIhTS5f6GlQXV_mgrm46H31WKbmAyQsCWhEmd2k",
        mint: "Fnak9KtTqxqWuw1AVrvgz9gSSB8kou36TJ4SM8jBC8CM",
    },
    brokenKey: {
        amount: 100_000,
        glb:  "https://arweave.net/gRstBO0S-Vnbdn22kypf03JOFZUmw7UCA3QRTHZZAq8",
        png:  "https://arweave.net/JJKLXJlhi-pYHxnEFKCMpEZ5TPU5vmmFvwEDlQ_pTAM",
        json: "https://arweave.net/weThkSgJJ7mjqU2YQc-3t-CTROXJeSF6pcJtpMmLpiA",
        mint: "vp8dyMzN6xp9MH1SdDKja8osmykhBX7ink3HtsHQZ4z",
    },
    blackKey: {
        amount: 100_000,
        glb:  "https://arweave.net/K8YTuVuGoZNRMxbXv_I8bv6rEKiR9jzmKCn5imsntN4",
        png:  "https://arweave.net/g-TP4O-jaipEg8M0jmZEuqE6y_WfHNOOmj6HuyqPIxs",
        json: "https://arweave.net/GsvjfMzEtyMtBz5yWlmoEOwmaHM7Z6KCHd2SWnPXfl0",
        mint: "86iXg8PGEAmbJ5LXYPTyM6jmzo556iabSUNAsgBYgp3c",
    },
    whiteKey: {
        amount: 100_000,
        glb:  "https://arweave.net/MPl_90mVS_QbSXEqkfpReyJUKHlvvPD4-v_JWR3o9H0",
        png:  "https://arweave.net/l-CB7NTWakvvH5a7S2tvEv01ezGIsHGFbD0VvJSJR-0",
        json: "https://arweave.net/N9LtB3oKMuXGm6SvgPfPZRwjzTf9whw5CYvQ8QH2f-s",
        mint: "61ChD33bkMjQXQPegeF6E6tPaBxDbEDReB8QfUbt3QHG",
    },
    blackChest: {
        amount: 100_000,
        glb:  "https://arweave.net/9g9YZs7d7NDBhwvFkO_Qdy7mwZ70n5yit2kcUw6aa_Q",
        png:  "https://arweave.net/VtE-w4_ww1eAp1-HAH56owHSxsax1Vk40mYXPgTQKfY",
        json: "https://arweave.net/NVpNebjJYLmaQYwScKrQXlpfJA8u7YR9_aszM7DaJBY",
        mint: "9V1WjJwKvejZGZTsApcTsvtv1jYe6qbon1zUMuQNmMNH",
    },
    whiteChest: {
        amount: 100_000,
        glb:  "https://arweave.net/XYi7FggKw5Dr2gfEWmAf7ZflLOEudl1yxJiY4vdvdM0",
        png:  "https://arweave.net/-8YP86JTb3P8rRI4k4opFS0EeBUU09bZgLQ0FNDTY-E",
        json: "https://arweave.net/k6eTZADu_Oey7_cYpjiXUumezPvmt-I17qKvMhnY7_0",
        mint: "6AqrJ6Dtd19YmxMqpBUyQYTXUxuvDNv6pqWQkZGvcxsE",
    },
    replayToken: {
        amount: 100_300,
        glb:  "https://arweave.net/MtyZ1n5soAmvC6NTaabaotEVdvxp6yKMjSX--yNYA0U",
        png:  "https://arweave.net/AVwhbS2Zc8sIOcgEIaTDCRhh-enHdpzNqZURNVFm_eI",
        json: "https://arweave.net/ZAVE289KpgBWtSnf4uKTuYSLDpZA9zCXbnHwjdn6yKI",
        mint: "HZTitJ4BinZD1c7k7jm8Sr7Lv77SLaS94X2wozEPxqy1",
    },
    realTreasure: {
        amount: 100_000,
        glb:  "https://arweave.net/HR-ALR1ClAJzyQvVoJPvzDhxJADhYyukzME-SnqatjY",
        png:  "https://arweave.net/fH2z2n3Q5UwlpvyM4N79d6Bfo_ZDuZBSfKJOdbYfvHU",
        json: "https://arweave.net/6ZSHVElU3L3DNSTJEC3oVSg9GIeGoa5TNdvqgY69weY",
        mint: "3ZL7mndSPFPxoRGeZK8rgDGbNXYV6HJY5S75TH2cDrYL",
    },
    redHerring: {
        amount: 100_000,
        glb:  "https://arweave.net/hpaeDL3WmvF01O7Pw8YNZKmRGxdjpdYVfy744y8-Bio",
        png:  "https://arweave.net/-GqSJ5iZhIeTg70gmZEKp4_JxDwwBVapTaMJFi13Wgc",
        json: "https://arweave.net/KBikx5zef9qPidbYe4tZPe1pEXa3j1roDQp1y8UzN8w",
        mint: "DW6VFSakaAoThahEHvLZNFw4yECUcqtKnUeqw7GqVXxo",
    },
    fakeNoot: {
        amount: 1,
        json: "https://arweave.net/PDz6fhM2NVv7jtKFC-d5aBBygL-qdauYxHeyArXPUrE",
        mint: "",
    },
    clue1: {
        amount: 1,
        png:  "https://arweave.net/anEbj2gI1xqqr7raf40lgWgUjVuzRqn8nDcenxVlnL4",
        json: "https://arweave.net/Jm19jKvk40xvokZsvo6LJaAG9iiG957skpGJ-dyt8i8",
        mint: "",
    },
    clue2: {
        amount: 1,
        png:  "https://arweave.net/euCxtEweDD7jR8BLjb97WxB3vGYcjMhRs4eZxKCBaTE",
        json: "https://arweave.net/KxUzJzW7-9F28eeuYpi1SxsLZDNyDZTmalhH7SGl_B0",
        mint: "",
    },
    clue3: {
        amount: 1,
        png:  "https://arweave.net/5S203RnAfGJCpnpFITjen5jnfVSn3J81ygRMJO5MhPU",
        json: "https://arweave.net/8oGeRs9lbky0Y_AZaMjWZxurTUjo47OWGnJrq99Ry28",
        mint: "",
    },
    clue4: {
        amount: 1,
        png:  "https://arweave.net/FmtXHdwu7_c9-6z_6zq3xN3R89d7djpGxbHLZpW9QLQ",
        json: "https://arweave.net/38-4vWJRLKLr8mf6aspegngBygK6TAO6r-zyP8ffWHQ",
        mint: "",
    },
    clueTitle: {
        amount: 1,
        png:  "https://arweave.net/bHO8CxEOZEcwx42Oej6F3HsjPXF8uYY8YMq_0n0OtO8",
        json: "https://arweave.net/ti41k3o4eYdgsabLKywCgtr4XRQLfKhOvQvbJZb7GhI",
        mint: "",
    },
    greenChest: {
        amount: 1,
        glb:  "https://arweave.net/88Nq6kThK6EzlNavEmo0riwvC1vTgstPxCi4j_JhmQw",
        json: "https://arweave.net/O2R_zLn2Av4UlW1K5Y_vWNVxGMKkPpAHXBanYLkk1_g",
        mint: "",
    },
    blueChest: {
        amount: 1,
        glb:  "https://arweave.net/9iBVnYBlOmHaf41i3LQ6-lDrXVs76jpbe69NjJRXaho",
        json: "https://arweave.net/hBlhHhmZuChi6mh1MrPQwfh6sKkGN0eXRTmdLoAkPuQ",
        mint: "",
    },
    purpleChest: {
        amount: 1,
        glb:  "https://arweave.net/JAPkROSTvxeFmG5mY3n9RfzMgKXf3qNuM9DrbheD75k",
        json: "https://arweave.net/lPDIXwXSK2eo3axwvpAKqbvWl-J9Ru6nOr_6_6RyNvY",
        mint: "",
    },
}