
export const ITEMS = {
    config: {
        collection: "93AM1qra2a8mRjz8KQ4ij2D1GTZaB2Ct62jUzyhtFwji",
        helper_collection: "ARFqPyjV5WA7Nu2bYqbEaeE8gjWrnN11ddXaHXmxq2d3",
        game: "FABt9886NbLDkfJReCNw4EicD2zPoYVC25jkmMyGXvUP"
    },
    solape: {
        amount: 100_000,
        json: "https://arweave.net/PHUINOgLilPQTaoTwDExLsygXtpti8pS8l10Hk9iF4U",
        mint: "DEAj8PGJrszPvzoFEihCfNxcFTjEsSqGiwaFgUwehPz2",
    },
    collection: {
        amount: 1,
        png:  "https://arweave.net/bxb0QFRZMl_zQDsKou0pbCMPQpxNZZSmfYXT1_A6MSk",
        json: "https://arweave.net/2Rydx48ahCOCM8yNCMpelXtU3c3vVd-T4Q54DhaU32Y",
        mint: "93AM1qra2a8mRjz8KQ4ij2D1GTZaB2Ct62jUzyhtFwji",
    },
    blueKey: {
        amount: 100_000,
        glb:  "https://arweave.net/4o3efioXVTMYAXCerFtpiYBdDzVOuPb4VxQGHsncfk4",
        png:  "https://arweave.net/gN9IcD4T4l7d71c1v5xTlVsvn0ByT-QyRNI3DE_002c",
        json: "https://arweave.net/XXhZKugN3l_N1A5NwhGImQcv_vbzHnbf2OoqrIoc5-k",
        mint: "27zp1EbjTnzL6vFckoTXKng54piUyr77pTKUR2ktT9Qb",
    },
    greenKey: {
        amount: 100_000,
        glb:  "https://arweave.net/tkoOiBTlSuX-Y6W9lR2UB-3VVGyxMijnGe4Ld2k8fU0",
        png:  "https://arweave.net/_MGeR0cyzolMNtWYrIDRQCEhi-27UmlizGVNhy7Fih4",
        json: "https://arweave.net/7qawsjan95U-XzSDurWd5ZiwnrdrQI16cXu6oEBhzAI",
        mint: "JCcLJCKxuvwTeKCzAweaDuXwUqaRBtWi6BJuBCi21MtF",
    },
    purpleKey: {
        amount: 100_000,
        glb:  "https://arweave.net/yKQlwpI5K7PdDAmCfmFR6v_oWzKh0wjFtlDF25QtRks",
        png:  "https://arweave.net/SIO8pPCSCsqg0kM9fGNXOQohDHhNPJ8n8Lwv_tjyfQg",
        json: "https://arweave.net/LRMSkMic55HUHgxt_wIF4B0kz_0J1VcZY9bzsOQTfRI",
        mint: "2cpDi9tK6txAH83hhF9wMr7WqdJByHegjbh4PxFVknyv",
    },
    brokenKey: {
        amount: 100_000,
        glb:  "https://arweave.net/gRstBO0S-Vnbdn22kypf03JOFZUmw7UCA3QRTHZZAq8",
        png:  "https://arweave.net/JJKLXJlhi-pYHxnEFKCMpEZ5TPU5vmmFvwEDlQ_pTAM",
        json: "https://arweave.net/dlF16GZA74q3pRytWjif9yLxoG9VfTd4-bB0mvnXv-k",
        mint: "BqToRRuffJa1nhy2ozy5L9BaqaTVCgq47S9w28Md6HYs",
    },
    blackKey: {
        amount: 100_000,
        glb:  "https://arweave.net/K8YTuVuGoZNRMxbXv_I8bv6rEKiR9jzmKCn5imsntN4",
        png:  "https://arweave.net/g-TP4O-jaipEg8M0jmZEuqE6y_WfHNOOmj6HuyqPIxs",
        json: "https://arweave.net/9_-tVwfsr8OCjAR6owefuIRaw66Mef5Gvy17hY2pjcA",
        mint: "8vn6D45BqpxHYbu5QPbKypUztvrA9YERsBda5Hbox2Lt",
    },
    whiteKey: {
        amount: 100_000,
        glb:  "https://arweave.net/MPl_90mVS_QbSXEqkfpReyJUKHlvvPD4-v_JWR3o9H0",
        png:  "https://arweave.net/l-CB7NTWakvvH5a7S2tvEv01ezGIsHGFbD0VvJSJR-0",
        json: "https://arweave.net/TQj24Sjh3jQgGMlTwK3iRltdLWlVZ5Cvdn0Mnny9eDQ",
        mint: "5X82vXfWg4RWy9RymE2BbVBNxuhCSoqoVh9TtXfx51L2",
    },
    blackChest: {
        amount: 100_000,
        glb:  "https://arweave.net/9g9YZs7d7NDBhwvFkO_Qdy7mwZ70n5yit2kcUw6aa_Q",
        png:  "https://arweave.net/VtE-w4_ww1eAp1-HAH56owHSxsax1Vk40mYXPgTQKfY",
        json: "https://arweave.net/PkbNFqvSEWc2CcN4Dn0-1DIQm_EF3HabXGrwD46akxs",
        mint: "HkNhhakjJNoewms2e2yES3DRFpGDQ9C4cDoA3LwryJGi",
    },
    whiteChest: {
        amount: 100_000,
        glb:  "https://arweave.net/XYi7FggKw5Dr2gfEWmAf7ZflLOEudl1yxJiY4vdvdM0",
        png:  "https://arweave.net/-8YP86JTb3P8rRI4k4opFS0EeBUU09bZgLQ0FNDTY-E",
        json: "https://arweave.net/QZweORO0axxwB8OMRYhUK7B8ntgmwZnGtWKYfNVBe8Y",
        mint: "ALVHiPAbFibDdFGxUwogvqMKa5FoRkSFipAyDqmU7NS8",
    },
    replayToken: {
        amount: 100_300,
        glb:  "https://arweave.net/MtyZ1n5soAmvC6NTaabaotEVdvxp6yKMjSX--yNYA0U",
        png:  "https://arweave.net/AVwhbS2Zc8sIOcgEIaTDCRhh-enHdpzNqZURNVFm_eI",
        json: "https://arweave.net/ZF6r1pKXBAnGfO9R8tletIFgiOPYYMAqBKQHhdBftTY",
        mint: "H1FAJcnpuWQQmbvqecyAgFZnC8daP27ALKyvAkgebYzh",
    },
    realTreasure: {
        amount: 100_000,
        glb:  "https://arweave.net/HR-ALR1ClAJzyQvVoJPvzDhxJADhYyukzME-SnqatjY",
        png:  "https://arweave.net/fH2z2n3Q5UwlpvyM4N79d6Bfo_ZDuZBSfKJOdbYfvHU",
        json: "https://arweave.net/w_3hJXfAvKz1ryxyvRkgJx1FIRhOkXVZ9H1uAUolKGM",
        mint: "BcKDpADLTnHoeNgAXxyKdWmMkd4iTxyA4XV4kYVqeWqh",
    },
    redHerring: {
        amount: 100_000,
        glb:  "https://arweave.net/hpaeDL3WmvF01O7Pw8YNZKmRGxdjpdYVfy744y8-Bio",
        png:  "https://arweave.net/-GqSJ5iZhIeTg70gmZEKp4_JxDwwBVapTaMJFi13Wgc",
        json: "https://arweave.net/C3v1i4Qd7xn7Vqi0QC829N3bp0B6kQ0LVzaTdbMlcj8",
        mint: "8p7H4N3gvbSo7UKZbA3kvA82vTzbSnuhVuJMNyaASqD9",
    },
    fakeNoot: {
        amount: 1,
        json: "https://arweave.net/DxiyfXrJOlLHPHszlSSdK-nXv0Z7GeNZ8ylJiXkrNes",
        mint: "7DbhgaKRv4c9WWpGdkNy2S7kfz2voHvCiGfFezDAzmQP",
    },
    clue1: {
        amount: 1,
        png:  "https://arweave.net/anEbj2gI1xqqr7raf40lgWgUjVuzRqn8nDcenxVlnL4",
        json: "https://arweave.net/MyOjvcD2MaxMe0-jJccnIN29MADM-x32DAiN3wCR-xw",
        mint: "HNXPZTB1zSLiWVuTatCwrA2ZgHDwUN7nM4zwWBZJQdxf",
    },
    clue2: {
        amount: 1,
        png:  "https://arweave.net/euCxtEweDD7jR8BLjb97WxB3vGYcjMhRs4eZxKCBaTE",
        json: "https://arweave.net/tfNCtsNeeXq9qPxPF5NC4RmwDwMXIWXAdkDlv1TGscU",
        mint: "79up9JLwCxck2mf5ybzSmV7R3SHEj6aNT3AWPu7ahM1i",
    },
    clue3: {
        amount: 1,
        png:  "https://arweave.net/5S203RnAfGJCpnpFITjen5jnfVSn3J81ygRMJO5MhPU",
        json: "https://arweave.net/84xg_lF8TRTQVQ9VKBejn7TAOzv1pVWEvDcYd6SuuFU",
        mint: "73Q5cBvG1PGwr9xTWBVaLkSy1AHbv1Bdv2dP6aYxLyrq",
    },
    clue4: {
        amount: 1,
        png:  "https://arweave.net/FmtXHdwu7_c9-6z_6zq3xN3R89d7djpGxbHLZpW9QLQ",
        json: "https://arweave.net/PpHciuIj0RIrL0PtVORYNKpzxgMNloaeeVejBN5j1u0",
        mint: "J7zp7X7Pge7ehbau2KCSvSH3aysZKHWsdE1WZJ35ZW17",
    },
    clueTitle: {
        amount: 1,
        png:  "https://arweave.net/bHO8CxEOZEcwx42Oej6F3HsjPXF8uYY8YMq_0n0OtO8",
        json: "https://arweave.net/Tjoi4uMEBRHb0Bu1ce4iKMOEwfR7I3KE8ZgUQsYzL9k",
        mint: "8skguXAYnLAhmx5sMbHJVhXcb7Cd27s62VL6B8GgMWxt",
    },
    greenChest: {
        amount: 1,
        glb:  "https://arweave.net/88Nq6kThK6EzlNavEmo0riwvC1vTgstPxCi4j_JhmQw",
        json: "https://arweave.net/5ZJ2Y97gBaJdYp1P-zNcqTlhDFXp2q5K21mwdGgjyLM",
        mint: "2G5T3dhjwp8WCAs4W44KfW1bVJESe8ZHxHDkjytXPCa4",
    },
    greenChestFix: {
        amount: 1,
        glb:  "https://arweave.net/88Nq6kThK6EzlNavEmo0riwvC1vTgstPxCi4j_JhmQw",
        json: "https://arweave.net/M-MI3iIpwzLQYZ13jraT6LNetPT4wO2z-N5KmorJjm4",
        mint: "",
    },
    blueChest: {
        amount: 1,
        glb:  "https://arweave.net/9iBVnYBlOmHaf41i3LQ6-lDrXVs76jpbe69NjJRXaho",
        json: "https://arweave.net/vlTlTSzx_xBHWJObstiMxa310iKHk5YA62PApjtxkQ4",
        mint: "J7NeabhWP78HrDWKBJ9hH7ijXKhxhvTfCrnr7Hu1kc7A",
    },
    blueChestFix: {
        amount: 1,
        glb:  "https://arweave.net/9iBVnYBlOmHaf41i3LQ6-lDrXVs76jpbe69NjJRXaho",
        json: "https://arweave.net/mQRaHFyrdtBVeUlAUMi-aGnCzKAknwi9TmtTmawARVw",
        mint: "J7NeabhWP78HrDWKBJ9hH7ijXKhxhvTfCrnr7Hu1kc7A",
    },
    purpleChest: {
        amount: 1,
        glb:  "https://arweave.net/JAPkROSTvxeFmG5mY3n9RfzMgKXf3qNuM9DrbheD75k",
        json: "https://arweave.net/haSEU87jSTeUr6FYFYE4asW6O9816n8RvcvkaZncu1Q",
        mint: "EowBFyrTyZHD3HQQqehrWZmzoog9afNH4FnVsUk9o9LA",
    },
    purpleChestFix: {
        amount: 1,
        glb:  "https://arweave.net/JAPkROSTvxeFmG5mY3n9RfzMgKXf3qNuM9DrbheD75k",
        json: "https://arweave.net/mXdqUb_saDynJfdlMjCi0Q_A52I6iw4l5Mjby20lJqA",
        mint: "EowBFyrTyZHD3HQQqehrWZmzoog9afNH4FnVsUk9o9LA",
    },
}