[features]
seeds = false
[programs.devnet]
soltreasure = "76k1YLcR4sPGoyoFk8BH38RDtCMAq6R61n9eEibDMq85"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/drkrueger/.config/solana/id.json"

[scripts]
test = "node tests/soltreasure.js"
