[features]
seeds = false
[programs.mainnet]
soltreasure = "GeHoPNKCypvmQy96y8DYxZBQf9gQiVW2NqVMUTxFG8a5"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "/Users/drkrueger/.config/solana/programs/sol-treasure.json"

[scripts]
test = "ts-node tests/tests.ts"